apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/project-999ca28f-35e8-45ea-8b7/newsflow/newsflow:latest
        command: ["python", "app/app.py"]
        ports:
        - containerPort: 7860
        env:
        - name: PYTHONPATH
          value: /app
        envFrom:
        - secretRef:
            name: newsflow-env
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 80
    targetPort: 7860
